# Generated by Django 3.2.25 on 2024-05-25 03:14

from django.db import migrations

def load_sql_from_file(apps, schema_editor):
    with open('rename_columns.sql', 'r') as file:
        sql = file.read()
    schema_editor.execute(sql)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_sql_from_file),
    ]
