# Generated by Django 3.2.25 on 2024-05-25 03:14

from django.db import migrations
import os

def load_sql_from_file(apps, schema_editor):
    # Get the directory where this migration file is located
    current_dir = os.path.dirname(__file__)
    # Construct the path to the SQL file
    sql_file_path = os.path.join(current_dir, 'cleanup.sql')

    # Open and read the SQL file
    with open(sql_file_path, 'r') as file:
        sql = file.read()
    # Execute the SQL
    schema_editor.execute(sql)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_sql_from_file),
    ]
