# Generated by Django 3.2.25 on 2024-06-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abandontrips',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='commentlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drivercomments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='infolinks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='infolinksposition',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restrictedcharges',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicereservations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicereservationsdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shoptasks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='specialnotice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tempmassemails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tripdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehiclebrand',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehiclecomments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehiclelimit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'managed': True},
        ),
    ]
