# Generated by Django 3.2.25 on 2024-06-14 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20240611_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abandontrips',
            options={'managed': True, 'verbose_name': 'Abandon Trip', 'verbose_name_plural': 'Abandon Trips'},
        ),
        migrations.AlterModelOptions(
            name='commentlog',
            options={'managed': True, 'verbose_name': 'Comment Log', 'verbose_name_plural': 'Comment Logs'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'managed': True, 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': True, 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='drivercomments',
            options={'managed': True, 'verbose_name': 'Driver Comment', 'verbose_name_plural': 'Driver Comments'},
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'managed': True, 'verbose_name': 'Global Setting', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='infolinks',
            options={'managed': True, 'verbose_name': 'Info Link', 'verbose_name_plural': 'Info Links'},
        ),
        migrations.AlterModelOptions(
            name='infolinksposition',
            options={'managed': True, 'verbose_name': 'Info Link Position', 'verbose_name_plural': 'Info Links Positions'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': True, 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'managed': True, 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='restrictedcharges',
            options={'managed': True, 'verbose_name': 'Restricted Charge', 'verbose_name_plural': 'Restricted Charges'},
        ),
        migrations.AlterModelOptions(
            name='servicereservations',
            options={'managed': True, 'verbose_name': 'Service Reservation', 'verbose_name_plural': 'Service Reservations'},
        ),
        migrations.AlterModelOptions(
            name='servicereservationsdetails',
            options={'managed': True, 'verbose_name': 'Service Reservation Detail', 'verbose_name_plural': 'Service Reservation Details'},
        ),
        migrations.AlterModelOptions(
            name='shoptasks',
            options={'managed': True, 'verbose_name': 'Shop Task', 'verbose_name_plural': 'Shop Tasks'},
        ),
        migrations.AlterModelOptions(
            name='specialnotice',
            options={'managed': True, 'verbose_name': 'Special Notice', 'verbose_name_plural': 'Special Notices'},
        ),
        migrations.AlterModelOptions(
            name='tempmassemails',
            options={'managed': True, 'verbose_name': 'Temp Mass Email', 'verbose_name_plural': 'Temp Mass Emails'},
        ),
        migrations.AlterModelOptions(
            name='tripdetails',
            options={'managed': True, 'verbose_name': 'Trip Detail', 'verbose_name_plural': 'Trip Details'},
        ),
        migrations.AlterModelOptions(
            name='vehiclebrand',
            options={'managed': True, 'verbose_name': 'Vehicle Brand', 'verbose_name_plural': 'Vehicle Brands'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecomments',
            options={'managed': True, 'verbose_name': 'Vehicle Comment', 'verbose_name_plural': 'Vehicle Comments'},
        ),
        migrations.AlterModelOptions(
            name='vehiclelimit',
            options={'managed': True, 'verbose_name': 'Vehicle Limit', 'verbose_name_plural': 'Vehicle Limits'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'managed': True, 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'managed': True, 'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'managed': True, 'verbose_name': 'Work Type', 'verbose_name_plural': 'Work Types'},
        ),
        migrations.AlterField(
            model_name='commentlog',
            name='comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departments',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drivercomments',
            name='comments_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicereservations',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shoptasks',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
