# Generated by Django 3.2.25 on 2024-06-19 02:18

import logging
import os
from django.db import migrations, models, connection

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

def load_sql_from_file(apps, schema_editor):
    current_dir = os.path.dirname(__file__)
    sql_file_path = os.path.join(current_dir, 'migrate_email_templates.sql')

    #logger.debug("Attempting to read SQL file from path: %s", sql_file_path)

    try:
        with open(sql_file_path, 'r', encoding='utf-8') as file:
            sql = file.read()

        #logger.debug("Successfully read SQL file. SQL content:\n%s", sql)

        with connection.cursor() as cursor:
            cursor.execute(sql)
            #logger.debug("Successfully executed SQL script.")

    except Exception as e:
        logger.error("Error executing SQL script: %s", e)
        raise e

class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20240614_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[
                    ('driver_registered', 'Driver Registered'), 
                    ('driver_activated', 'Driver Activated'), 
                    ('dept_cross_charge_notice', 'Dept. Cross Charge Notice'), 
                    ('vehicle_removed_for_service', 'Vehicle Removed for Service'), 
                    ('driver_deactivation_notice', 'Driver Deactivation Notice'), 
                    ('restore_suspended_driver', 'Restore Suspended Driver'), 
                    ('activate_restore_vehicle', 'Activate - Restore Vehicle'), 
                    ('permit_renewal', 'Permit Renewal'), 
                    ('late_trip_cancellation', 'Late Trip Cancellation'), 
                    ('abandon_notice_with_charge', 'Abandon Notice with Charge')
                ], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('variables', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'transport_email_template',
                'managed': True,
            },
        ),
        migrations.RunPython(load_sql_from_file),
    ]
