# Generated by Django 3.2.25 on 2025-01-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_emailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='planned_passenger_no',
            new_name='planned_passenger_count',
        ),
    ]
