# Generated by Django 3.2.25 on 2025-01-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_rename_passenger_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicles',
            constraint=models.CheckConstraint(check=models.Q(('active', True), ('sold', True), _negated=True), name='transport_vehicles_check_sold_inactive'),
        ),
    ]
